[project]
name = "core"
version = "0.1.0"
description = "The ai engine for the kortex app"
readme = "README.md"
license = "AGPL-3.0-or-later"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "beautifulsoup4>=4.14.3",
    "boto3>=1.42.15",
    "fastapi[standard]>=0.141.1",
    "google-genai>=2.18.0",
    "httpx>=0.28.1",
    "inngest>=0.5.19",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "pypdf>=6.15.0",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.21",
    "qdrant-client>=1.19.0",
    "redis>=8.1.0",
    "tavily-python>=0.7.27",
    "youtube-transcript-api>=1.2.4",
]
